# Generated by Django 3.1.1 on 2020-09-20 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='类别')),
                ('latin', models.CharField(default='', max_length=100, verbose_name='拉丁名')),
                ('map', models.ImageField(default='', upload_to='', verbose_name='地图')),
                ('level', models.CharField(blank=True, default='', max_length=200, verbose_name='保护等级')),
                ('genus', models.CharField(blank=True, default='', max_length=50, verbose_name='科属名')),
                ('location', models.CharField(blank=True, default='', max_length=500, verbose_name='分布')),
                ('macro', models.CharField(blank=True, default='', max_length=500, verbose_name='宏观构造特征')),
                ('micro', models.CharField(blank=True, default='', max_length=500, verbose_name='微观构造特征')),
                ('density', models.CharField(blank=True, default='', max_length=50, verbose_name='木材气干密度')),
                ('cross_img', models.ImageField(default='', upload_to='', verbose_name='横切面')),
                ('radial_img', models.ImageField(default='', upload_to='', verbose_name='径切面')),
                ('tang_img', models.ImageField(default='', upload_to='', verbose_name='弦切面')),
            ],
            options={
                'verbose_name': '红木种类',
                'verbose_name_plural': '红木种类',
            },
        ),
        migrations.CreateModel(
            name='Filters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='类型')),
                ('classes', models.CharField(max_length=200, verbose_name='树种')),
            ],
            options={
                'verbose_name': '红木筛选',
                'verbose_name_plural': '红木筛选',
            },
        ),
    ]
