# Generated by Django 2.2.1 on 2019-08-19 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redwood', '0003_aimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimages',
            name='redwood',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='redwood.Redwood'),
            preserve_default=False,
        ),
    ]
