# Generated by Django 2.2.1 on 2019-08-19 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redwood', '0004_aimages_redwood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redwood',
            name='classes',
        ),
    ]
