# Generated by Django 2.2.1 on 2019-08-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redwood', '0006_auto_20190819_1810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': '图片', 'verbose_name_plural': '图片'},
        ),
        migrations.AlterModelOptions(
            name='redwood',
            options={'verbose_name': '红木', 'verbose_name_plural': '红木'},
        ),
        migrations.RemoveField(
            model_name='redwood',
            name='location',
        ),
        migrations.AlterField(
            model_name='redwood',
            name='desc',
            field=models.CharField(max_length=200, verbose_name='描述'),
        ),
    ]
