# Generated by Django 3.0.3 on 2020-07-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('redwood', '0009_remove_images_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='redwood',
            name='type',
            field=models.CharField(default='', max_length=200, verbose_name='类别'),
        ),
    ]
