# Generated by Django 3.0.3 on 2020-07-12 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('redwood', '0010_redwood_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=200, verbose_name='描述')),
                ('type', models.CharField(max_length=20, verbose_name='类别')),
            ],
            options={
                'verbose_name': '红木种类',
                'verbose_name_plural': '红木种类',
            },
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': '红木图片', 'verbose_name_plural': '红木图片'},
        ),
        migrations.AlterField(
            model_name='images',
            name='redwood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redwood.Classes'),
        ),
        migrations.DeleteModel(
            name='Redwood',
        ),
    ]
