# Generated by Django 3.0.3 on 2020-07-31 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('redwood', '0011_auto_20200712_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='map',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
