# Generated by Django 3.0.3 on 2020-08-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('redwood', '0012_classes_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='desc',
            field=models.CharField(max_length=1000, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='map',
            field=models.ImageField(default='', upload_to='', verbose_name='地图'),
        ),
    ]
