# Generated by Django 3.0.3 on 2020-08-13 02:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('redwood', '0015_auto_20200813_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='density',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='木材气干密度'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='genus',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='科属名'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='level',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='保护等级'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='location',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='分布'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='macro',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='宏观构造特征'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='micro',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='微观构造特征'),
        ),
    ]
