# Generated by Django 3.0.3 on 2020-08-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('redwood', '0016_auto_20200813_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='cross_img',
            field=models.ImageField(default='', upload_to='', verbose_name='横切面'),
        ),
        migrations.AddField(
            model_name='classes',
            name='radial_img',
            field=models.ImageField(default='', upload_to='', verbose_name='径切面'),
        ),
        migrations.AddField(
            model_name='classes',
            name='tang_img',
            field=models.ImageField(default='', upload_to='', verbose_name='弦切面'),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
