# Generated by Django 3.0.3 on 2020-09-19 02:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('redwood', '0018_classes_latin'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='标签'),
        ),
    ]
