# Generated by Django 3.0.3 on 2020-09-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('redwood', '0019_classes_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='类型')),
                ('classes', models.CharField(max_length=200, verbose_name='树种')),
            ],
            options={
                'verbose_name': '红木筛选',
                'verbose_name_plural': '红木筛选',
            },
        ),
    ]
