# Generated by Django 3.0.3 on 2020-09-19 04:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('redwood', '0020_filters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='tag',
        ),
    ]
